temp_1=apply(a,1,names)
temp_2=apply(a,2,names)
library(caret)
createFolds(y=rep(1,100))
data(oil)
createResample(1:100, times = 10, list = TRUE)
createDataPartition(1:100)
groupKFold(1:100,k=10)
createTimeSlices(1:100,10)
t= list(data.frame(list(a=2,b=5)),data.frame(list(a=6,b=-2)))

d=do.call(rbind,t)
a=paste(c('a','b','c'))
length(a)
do.call(paste,list('a','b','c',sep='_'))
paste(x=c('a','b','c'),sep='_',collapse = NULL)
temp=c(a=1,b=2,c=3)
temp['d']
library(magrittr)
filtered=temp[c('a','d','b')] %>% na.omit
class(filtered)
filtered
ds=data.frame(a=c('a','b'),b=c('c','d'))
rownames(ds)=c('Rad 1','Rad 2')
apply(ds,MARGIN=1,FUN=paste,collapse=' ')
time = OTU_time_series(phyloseq_object,time_points = phyloseq_object@sam_data$Week)
time_2 = OTU_time_series(phyloseq_object,time_points = 'Week')
